CREATE DATABASE managedb;
USE managedb;

CREATE TABLE cProf
(
  Company VARCHAR(30) NOT NULL,
  Company_Address VARCHAR(100) NOT NULL,
  pID VARCHAR(20) NOT NULL,
  CONSTRAINT profPK PRIMARY KEY (pID)
);

CREATE TABLE Portfolio
(
  Portfolio_Name VARCHAR(30) NOT NULL,
  ptID VARCHAR(20) NOT NULL,
  CONSTRAINT portPK PRIMARY KEY (ptID)
);

CREATE TABLE Properties
(
  pName VARCHAR(30) NOT NULL,
  Address VARCHAR(100) NOT NULL,
  prID VARCHAR(20) NOT NULL,
  CONSTRAINT propPK PRIMARY KEY (prID)
);

CREATE TABLE Building
(
  bName VARCHAR(30) NOT NULL,
  bType VARCHAR(20) NOT NULL,
  bID VARCHAR(20) NOT NULL,
  prID VARCHAR(20),
  CONSTRAINT bPK PRIMARY KEY (bID),
  CONSTRAINT prFK FOREIGN KEY (prID) REFERENCES Properties(prID)
);

CREATE TABLE Units
(
  Capex VARCHAR(30) NOT NULL,
  uName VARCHAR(30) NOT NULL,
  unID VARCHAR(20) NOT NULL,
  bID VARCHAR(20),
  CONSTRAINT unPK PRIMARY KEY (unID),
  CONSTRAINT bFK FOREIGN KEY (bID) REFERENCES Building(bID)
);

CREATE TABLE shows
(
  pID VARCHAR(20) NOT NULL,
  ptID VARCHAR(20) NOT NULL,
  CONSTRAINT pptPK PRIMARY KEY (pID, ptID),
  CONSTRAINT pFK FOREIGN KEY (pID) REFERENCES cProf(pID),
  CONSTRAINT ptsFK FOREIGN KEY (ptID) REFERENCES Portfolio(ptID)
);

CREATE TABLE has
(
  ptID VARCHAR(20) NOT NULL,
  prID VARCHAR(20) NOT NULL,
  CONSTRAINT pprPK PRIMARY KEY (ptID, prID),
  CONSTRAINT portFK FOREIGN KEY (ptID) REFERENCES Portfolio(ptID),
  CONSTRAINT propFK FOREIGN KEY (prID) REFERENCES Properties(prID)
);

CREATE TABLE Users
(
  Pass VARCHAR(20) NOT NULL,
  Username VARCHAR(20) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  uID VARCHAR(20) NOT NULL,
  pID VARCHAR(20) NOT NULL,
  Administrates_uID VARCHAR(20),
  CONSTRAINT uuPK PRIMARY KEY (uID),
  CONSTRAINT puFK FOREIGN KEY (pID) REFERENCES cProf(pID),
  CONSTRAINT uaFK FOREIGN KEY (Administrates_uID) REFERENCES Users(uID)
);
